### ISSUE TITLE
what patches are used here?

### ISSUE THREAD

**Issue by freedom1b2830** [archlinuxhardened/selinux-policy-arch#2]
what patches are used here?

**Comment by fishilico** [comment]
Hello,
A few years ago, there were some patches to label programs in `/usr/bin` which were only labeled in `/bin` or `/usr/sbin` in upstream refpolicy. These patches have all been upstreamed, and nowadays there are only two patches left (cf. https://github.com/archlinuxhardened/selinux-policy-arch/commits/2.20220520):

- https://github.com/archlinuxhardened/selinux-policy-arch/commit/c0b2a4b4694e3046ca04457d00307686a8717786 defines the default configuration of Arch Linux.
- https://github.com/archlinuxhardened/selinux-policy-arch/commit/6c7d3e2fb54f2b3d949ceedf2317ffd0c1d0e176 adds Arch Linux to the test matrix used by GitHub Actions Continuous Integration system.

**Comment by freedom1b2830** [comment]
Please add 2 builds for mls/mcs policy.

Thanks for the answer.
